data:
  name: CpuRecDataset
  params:
    dataset_path: cpu_rec/cpu_rec_corpus
    feature_csv_path: cpu_rec-features.csv
    per_architecture_limit: null
    max_file_splits: 1000
    file_byte_read_limit: 512

transforms:
  name: GrayScaleImage
  params:
    dimx: 32
    dimy: 16
    normalize: True
    duplicate_to_n_channels: null

model:
  name: Simple2d
  params:
    num_classes: 2
    dropout_rate: 0.3

validator:
  name: logo_cv
  wandb_project_name: Simple2d

training:
  optimizer: AdamW
  learning_rate: 0.0001
  weight_decay: 0.01
  criterion: CrossEntropyLoss
  batch_size: 64
  epochs: 2
