data:
  name: CpuRecDataset
  params:
    dataset_path: cpu_rec/cpu_rec_corpus
    feature_csv_path: cpu_rec-features.csv
    per_architecture_limit: null
    max_file_splits: 1000
    file_byte_read_limit: 512

transforms:
  name: Vector1D
  params:
    length: 512

model:
  name: Simple1d
  params:
    input_length: 512
    num_classes: 2
    dropout_rate: 0.3

validator:
  name: logo_cv
  wandb_project_name: Simple1d

training:
  optimizer: AdamW
  learning_rate: 0.0001
  weight_decay: 0.01
  criterion: CrossEntropyLoss
  batch_size: 64
  epochs: 2
