data:
  name: BuildCrossDataset
  params:
    dataset_path: buildcross/text_bin
    feature_csv_path: buildcross/labels.csv
    per_architecture_limit: null
    file_byte_read_limit: 512
    max_file_splits: 10000

transforms:
  name: Vector1D
  params:
    length: 512

model:
  name: Simple1dEmbedding
  params:
    input_length: 512
    num_classes: 2
    dropout_rate: 0.3

validator:
  name: train_test_split
  wandb_project_name: buildcross-train-test
  seed: 42
  train_split_size: 0.8

training:
  optimizer: AdamW
  learning_rate: 0.0001
  weight_decay: 0.01
  criterion: CrossEntropyLoss
  batch_size: 64
  epochs: 2
