target_feature: endianness

data:
  name: CpuRecDataset
  params:
    dataset_path: cpu_rec/cpu_rec_corpus
    feature_csv_path: ISAdetect-features.csv
    per_architecture_limit: null
    file_byte_read_limit: 512

transforms:
  name: Vector1D
  params:
    length: 512

model:
  name: EmbeddingAndCNNModel
  params:
    input_length: 512
    num_classes: 2
    dropout_rate: 0.3

validator:
  name: LOGO_architecture_skip

training:
  optimizer: AdamW
  learning_rate: 0.001
  weight_decay: 0.0001
  criterion: CrossEntropyLoss
  batch_size: 64
  epochs: 2
