target_feature: endianness

data:
  name: ISAdetectDataset
  params:
    dataset_path: ../dataset/ISAdetect/ISAdetect_full_dataset
    feature_csv_path: ../dataset/ISAdetect-features.csv
    per_architecture_limit: null
    file_byte_read_limit: 10000
    use_code_only: True

transforms:
  name: Vector1D
  params:
    length: 512

model:
  name: EmbeddingAndCNNModel
  params:
    input_length: 512
    num_classes: 2

validator:
  name: LOGO_architecture

training:
  optimizer: AdamW
  learning_rate: 0.001
  weight_decay: 0.0001
  criterion: CrossEntropyLoss
  batch_size: 32
  epochs: 2
