data:
  name: ISAdetectDataset
  params:
    dataset_path: ISAdetect/ISAdetect_full_dataset/
    feature_csv_path: ISAdetect-features.csv
    per_architecture_limit: null
    file_byte_read_limit: 2304
    use_code_only: True

transforms:
  name: Vector1D
  params:
    length: 2304

model:
  name: ResNet50Embedding
  params:
    input_length: 2304
    num_classes: 23
    embedding_dim: 128
    vocab_size: 256

validator:
  name: kfold_cv
  wandb_project_name: ResNet50Embedding
  n_splits: 5

training:
  optimizer: AdamW
  learning_rate: 0.0001
  weight_decay: 0.01
  criterion: CrossEntropyLoss
  batch_size: 64
  epochs: 5
