data:
  name: BuildCrossDataset
  params:
    dataset_path: buildcross/text_bin
    feature_csv_path: buildcross/labels.csv
    per_architecture_limit: null
    file_byte_read_limit: 1024
    max_file_splits: 10000

transforms:
  name: Vector1D
  params:
    length: 1024

model:
  name: ResNet50Embedding
  params:
    input_length: 1024
    num_classes: 40
    embedding_dim: 128
    vocab_size: 256

validator:
  name: kfold_cv
  wandb_project_name: ResNet50Embedding
  n_splits: 5

training:
  optimizer: AdamW
  learning_rate: 0.0001
  weight_decay: 0.01
  criterion: CrossEntropyLoss
  batch_size: 64
  epochs: 5
